routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('image/{type}/{filename}', 'ImageController@index')
    ->name('image')
;

Route::get('thumb/{w}x{h}/{type}/{filename}', 'ImageController@thumb')
    ->where('w', '5|50|100|150|300|400|275|250')
    ->where('h', '5|50|100|150|300|280|180|250')
    ->name('thumb')
;

Route::get('start', function() {
    dd(Artisan::call("migrate:refresh", [
        '--force' => true,
    ]));
});

# Admin Routes!
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin'], function () {

    Route::get('/', 'HomeController@index')->name('.main');

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('.login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('.logout');
    Route::get('logout', function () {
        Auth::logout();
        return redirect('/admin');
    })->name('.logout');

    Route::group(['middleware' => ['auth.admin']], function () {

        #if(function_exists('admin_resource')) {
            admin_resource('users', 'UsersController', 'users');
            admin_resource('translations', 'TranslationsController', 'translations');
            admin_resource('services', 'ServicesController', 'services');


//            Route::get('categories/{type}', 'CategoriesController@index')->name('.categories');
//            Route::delete('categories/{type}/{id}', 'CategoriesController@destroy')->name('categories.delete');
//    //        Route::post('categories/{type}/sort', 'CategoriesController@sort')->name('images.sort');
//            Route::put('categories/{type}', 'CategoriesController@store')->name('categories.store');

            admin_resource('categories/{type}', 'CategoriesController', 'categories');
            Route::post('categories/{type}/sort', 'CategoriesController@sort');
            admin_resource('gallery/{type}', 'GalleryController', 'gallery');
            admin_resource('projects', 'ProjectsController', 'projects');
            admin_resource('news', 'NewsController', 'news');

            admin_resource('neighborhoods', 'NeighborhoodsController', 'neighborhoods');
            Route::get('neighborhoods/list/{city_id}', 'NeighborhoodsController@list')->name('.neighborhoods.list');
            admin_resource('mosques', 'MosquesController', 'mosques');
            admin_resource('companies', 'CompaniesController', 'companies');
            admin_resource('products', 'ProductsController', 'products');
            admin_resource('places', 'PlacesController', 'places');
            admin_resource('pages', 'PagesController', 'pages');
            admin_resource('orders', 'OrdersController', 'orders');
        #}

        Route::get('contacts/export', 'ContactsController@export')->name('.contacts.export');
        Route::post('contacts/data', 'ContactsController@data')->name('.contacts.data');
        Route::resource('contacts', 'ContactsController');

        Route::get('options', 'OptionsController@index')->name('.options.index');
        Route::post('options', 'OptionsController@update')->name('.options.update');

    });

});

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localizationRedirect', 'localeViewPath' ],
], function() {

    Route::get('/', 'HomeController@index')->name('home');

    // USER
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::get('profile/edit', 'UserController@edit')->name('edit.profile');
    Route::post('profile', 'UserController@save')->name('save.profile');
    Route::get('units', 'UserController@units')->name('units');
    Route::get('unit/{id}', 'UserController@unit')->name('unit');
    Route::get('payments/{id}', 'UserController@payments')->name('payments');
    Route::get('logout', function () {
        Auth::logout();
        return redirect('/profile');
    })->name('user.logout');

    Route::get('/news', 'NewsController@index')->name('news');
    Route::post('/order', 'OrdersController@index')->name('order.send');
    Route::get('/news/{id}', 'NewsController@article')->name('article');

    Route::get('/gallery', 'GalleryController@index')->name('gallery');
    Route::get('/projects', 'ProjectsController@index')->name('projects');
    Route::get('/projects/{id}', 'ProjectsController@projects')->name('projects.category');
    Route::get('/project/{id}', 'ProjectsController@project')->name('project');
    Route::get('/page/{slug}', 'PagesController@index')->name('page');
    Route::get('/{type}/{id}', 'CategoriesController@index')->name('category');

});

Auth::routes();

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $connection = 'mysql';

    function getUrlAttribute() {
        return route('category', [$this->type, $this->id]);
    }

    function getCountNewsAttribute() {
        return News::whereCategoryId($this->id)->count();
    }

    function subCategories() {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    function projects() {
        return $this->hasMany(Project::class);
    }

    function getImageAttribute() {
        return route('thumb', [ '100', '100','category', $this->file]);
    }

    function getImageUrlAttribute() {
        return route('image', [ 'category', $this->file]);
    }
}

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $connection = 'mysql';

    public function category() {
        return $this->belongsTo(Category::class);
    }

    function getUrlAttribute() {
        return route('article', $this->id);
    }

    function getImageUrlAttribute() {

        $images = json_decode($this->images);
        if(sizeof($images) == 0) return '';

        return route('image', ['news', $images[0]->image]);
    }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\News;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class NewsController extends Controller
{

    function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (!can(['add-news', 'edit-news', 'delete-news'])) {
                return redirect(route('admin.main'));
            }
            return $next($request);
        });

        \View::share('current', 'news');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $newsData = $this->data()->getData();
        $news = $newsData->data;
        $recordsTotal = $newsData->recordsTotal;
        return view('admin.news', compact('news', 'recordsTotal'));
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function data()
    {
        $isOrder = \request()->get('order');

        if ($isOrder) $query = News::query();
        else $query = News::query()->orderBy('id','desc')->limit(10);

        return Datatables::of($query)
            ->addColumn('image_url', function (News $news) {
                $images = json_decode($news->images);
                if(sizeof($images) == 0) return '';
                return img(route('image', ['news', $images[0]->image]), '', " style='width: 75px' ");
            })
            ->addColumn('options', function (News $news) {

                $back = "";

                if (can(['edit-news', 'delete-news'])) {
                    if ( can('edit-news') ) $back .= data_edit_btn($news);
                    if ( can('delete-news') ) $back .= data_delete_btn($news);
                } else $back .= '-';

                return $back;
            })
            ->rawColumns(['options', 'image_url', 'name'])
            ->make(true);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (!auth()->user()->can('add-news')) return no_permission();

        $this->validate($request, [
            'title'         => 'required|max:255',
            'category_id'       => 'required',
            'content'   => 'required',
        ]);

        $news = new News();
        $news->title = $request->title;
        $news->category_id = $request->category_id;
        $news->content = $request->get('content');
        $news->content_ar = $request->get('content_ar');
        $news->title_ar = $request->get('title_ar');


        $images = $request->has('images') ? $request->get('images') : [];

        if( $request->hasFile('newsImages'))
            foreach ($request->file('newsImages') as $file) {
                if ($file->isValid()) {
                    $path = $file->storePublicly('news');
                    if( $path ) {
                        $images[] = str_replace('news/', '', $path);
                    }
                }
            }

        $values = [];
        foreach ($images as $image) {
            $values[] = [
                'image' => $image,
            ];
        }

        $news->images = json_encode($values);

//        if ($request->hasFile('file')) {
//            if ($request->file('file')->isValid()) {
//                $path = $request->file->storePublicly('news');
//                if( $path ) {
//                    $news->image = str_replace('news/', '', $path);
//                }
//            }
//        } else {
//            return response()->json([
//                'errors' => [
//                    'file' => 'Please choose the image',
//                ]
//            ], 422);
//        }

        $news->save();

        return $news;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $news = News::findOrFail($id);
            return response()->json([
                "success"   => true,
                "data"      => $news
            ]);
        } catch (\Exception $e) {
            return response()->json([
                "success"   => false,
                "message"   => __('admin.not_found')
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!auth()->user()->can('edit-news')) return no_permission();

        $this->validate($request, [
            'title'             => 'required|max:255',
            'category_id'       => 'required',
            'content'       => 'required',
        ]);

        $news = News::find($id);
        $news->title = $request->title;
        $news->category_id = $request->category_id;
        $news->content = $request->get('content');
        $news->content_ar = $request->get('content_ar');
        $news->title_ar = $request->get('title_ar');
        $images = $request->has('images') ? $request->get('images') : [];

        if( $request->hasFile('newsImages'))
            foreach ($request->file('newsImages') as $file) {
                if ($file->isValid()) {
                    $path = $file->storePublicly('news');
                    if( $path ) {
                        $images[] = str_replace('news/', '', $path);
                    }
                }
            }

        $values = [];
        foreach ($images as $image) {
            $values[] = [
                'image' => $image,
            ];
        }

        $news->images = json_encode($values);

        $news->save();

        return $news;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        if (!auth()->user()->can('delete-news')) return no_permission();

        try{
            $news = News::findOrFail($id);
            $news->delete();
            return response()->json([
                "success"   => true
            ]);
        } catch (\Exception $e) {
            return response()->json([
                "success"   => false,
                "message"   => __('admin.not_found')
            ]);
        }
    }
}

app/Http/Controllers/NewsController.php
<?php namespace App\Http\Controllers;

use App\Category;
use App\News;

class NewsController extends Controller
{

    public function index() {
        $news = News::paginate(10);
        return view('news.index', compact('news'));
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function article( $id )
    {
        $news = News::findOrFail($id);
        $categories = Category::whereType('news')->get();
        $related_news = News::where('id', '!=', $id)->limit(3)->get();
        return view('news.show', compact('news', 'categories', 'related_news'));
    }

}

resources/views/news/index.blade.php
@extends('layouts.app')

@section('body_class') blog @stop

@section('content')

    <section class=" container">
        <div class="row">
            <div class="col-lg-12 headline">
                <h1>{{ trans('news.last_news') }}</h1>
                <hr />
            </div>
        </div>

        <div class="row">

            <div class="col-md-9">
                @foreach($news as $n)
                <article class="row">
                    <aside class="col-xs-1">
                        <div class="box date">
                            <div class="day">
                                {{ $n->created_at->format('d') }}
                            </div>
                            <div class="rest">
                                {{ $n->created_at->format('M, Y') }}
                            </div>
                        </div>

                    </aside>
                    <div class="content col-xs-11">
                        <div class="col-xs-4">
                            <img src="{{ $n->image_url }}" >
                        </div>
                        <div class="col-xs-8">
                            <h3>{{ $n->{_trans('title')} }}</h3>
                            <p>{{ str_limit(strip_tags($n->{_trans('content')})) }}</p>
                            <a href="{{ $n->url }}" class="btn"><i class="fa fa-bars"></i>Read more</a>
                        </div>
                    </div>
                </article>
                @endforeach
            </div>

            <aside class="col-md-3">

                {{--<section class="popular">--}}
                    {{--<h4>Popular posts</h4>--}}
                    {{--@foreach($related_news as $related_new)--}}
                    {{--<article class="row">--}}
                        {{--<div class="col-md-4 col-xs-2">--}}
                            {{--<div class="photo"><img src="{{ $related_new->image_url }}" alt="thumbnail"></div>--}}
                        {{--</div>--}}
                        {{--<div class="col-md-8 col-xs-10">--}}
                            {{--<h5>{{ $related_new->{_trans('title')} }}</h5>--}}
                            {{--<aside>{{ $related_new->created_at->format('M d, Y') }}</aside>--}}
                            {{--<aside class="comments"><i class="fa fa-comments"></i> 23 comments</aside>--}}
                        {{--</div>--}}
                    {{--</article>--}}
                    {{--@endforeach--}}
                {{--</section>--}}

                {{--<section class="categories">--}}
                    {{--<h4>Categories</h4>--}}

                    {{--<div class="row">--}}
                        {{--<ul class="col-sm-12">--}}
                            {{--@foreach($categories as $category)--}}
                            {{--<li>--}}
                                {{--<a href="{{ $category->url }}">{{ $category->{_trans('title')} }} <span class="amount">({{ $category->count_news }})</span></a>--}}
                            {{--</li>--}}
                            {{--@endforeach--}}
                        {{--</ul>--}}
                    {{--</div>--}}
                {{--</section>--}}


            </aside>

        </div>


    </section>


@endsection

resources/views/news/show.blade.php
@extends('layouts.app')

@section('body_class') blog @stop

@section('content')

    <section class=" container">
        <div class="row">
            <div class="col-lg-12 headline">
                <h1>{{ $news->{_trans('title')} }}</h1>
                <hr />
            </div>
        </div>

        <div class="row">
            <div class="col-md-9">
                <article class="row">
                    <aside class="col-xs-1">
                        {{--<div class="box avatar">--}}
                            {{--<img src="{{ $news->image_url }}" class="" alt="Author" />--}}
                        {{--</div>--}}

                        <div class="box">
                            <i class="fa fa-camera"></i>
                        </div>
                        <div class="box date">
                            <div class="day">
                                {{ $news->created_at->format('d') }}
                            </div>
                            <div class="rest">
                                {{ $news->created_at->format('M, Y') }}
                            </div>
                        </div>

                    </aside>
                    <div class="content col-xs-11">
                        <img src="{{ $news->image_url }}" alt="Depositphotos_4578857_originala" />
                        <h3>{{ $news->{_trans('title')} }}</h3>
                        <p>{!! nl2br($news->{_trans('content')}) !!}</p>
                        {{--<button class="btn"><i class="fa fa-bars"></i>Read more</button>--}}
                    </div>
                </article>
            </div>

            <aside class="col-md-3">

                <section class="popular">
                    <h4>Popular posts</h4>
                    @foreach($related_news as $related_new)
                    <article class="row">
                        <div class="col-md-4 col-xs-2">
                            <div class="photo"><img src="{{ $related_new->image_url }}" alt="thumbnail"></div>
                        </div>
                        <div class="col-md-8 col-xs-10">
                            <h5>{{ $related_new->{_trans('title')} }}</h5>
                            <aside>{{ $related_new->created_at->format('M d, Y') }}</aside>
                            {{--<aside class="comments"><i class="fa fa-comments"></i> 23 comments</aside>--}}
                        </div>
                    </article>
                    @endforeach
                </section>

                <section class="categories">
                    <h4>Categories</h4>

                    <div class="row">
                        <ul class="col-sm-12">
                            @foreach($categories as $category)
                            <li>
                                <a href="{{ $category->url }}">{{ $category->{_trans('title')} }} <span class="amount">({{ $category->count_news }})</span></a>
                            </li>
                            @endforeach
                        </ul>
                    </div>
                </section>


            </aside>

        </div>


    </section>


@endsection